name: ci
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Document Version'
        required: true
        default: '0.3.0'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          token: ${{ secrets.ACTIONTOKEN }}
          submodules: true
          
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Intialiaze Python Env
        run: |
          pip install -r requirements.txt
          
      - name: Mike Version Snapshot
        run: |
          git fetch --all 
          git reset --hard origin/main 
          git pull 
          git config --global user.email ${{ secrets.GITUSEREMAIL }}
          git config --global user.name ${{ secrets.GITUSERNAME }}
          git submodule update --remote
          git commit -m "update submodules" || echo "No changes to commit"
          git push
          mike deploy --push --update-aliases ${{ github.event.inputs.version }} latest
          mike set-default --push latest
          git add *
          git commit * -m "update site"
          git push
      
      - name: Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUBUSER }}
          password: ${{ secrets.DOCKERHUBPASSWORD }}
          
      - name: Build && Push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            matrixorigin/matrixorigin.io.cn:${{ github.event.inputs.version }}
            matrixorigin/matrixorigin.io.cn:latest            
