name: lint

on:
  pull_request:

jobs:
  lint-docs:
    name: Lint Docs
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:

    - name: Get all changed markdown files
      id: changed-markdown-files
      uses: tj-actions/changed-files@v40
      with:
        files: |
           docs/**/*.md

    - name: Check out code
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: actions/checkout@v4
      with:
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        ref: ${{ github.event.pull_request.head.ref }}
        # Assume PRs are less than 20 commits
        fetch-depth: 20

    - name: Setup node
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install node deps
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        pnpm --version
        pnpm i --frozen-lockfile

    - name: Lint with markdownlint
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        npx markdownlint-cli2 ${{ steps.changed-markdown-files.outputs.all_changed_files }}

    - name: Lint with zhlint
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        npm run config:zhlint
        for file in ${{ steps.changed-markdown-files.outputs.all_changed_files }}; do
          npx zhlint $file
        done

    - name: Lint with autocorrect
      if: steps.changed-markdown-files.outputs.any_changed == 'true'
      run: |
        npm run lint:autocorrect ${{ steps.changed-markdown-files.outputs.all_changed_files }}
